services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./init-db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build: .
    ports:
      - "8000:8000"  # Port, na którym będzie działała aplikacja Django
    depends_on:
      - db  # Django będzie czekać na bazę danych
    volumes:
      - .:/app
    networks:
      - mynetwork
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000", "--noreload"]

volumes:
  db_data: {}

networks:
  mynetwork:
    driver: bridge
